train_chose: True # use en_train or en_test for training
GPU_ID: '0'
weight_path: "/storage1/user/ss/tmoji_tmp/weights_t_att.hdf5" # path to store the model weight
pretrain_path: "/storage1/user/ss/tmoji_tmp/" # for testing, load the pretrained model
embed_path: "/storage1/user/bull/tmoji_embedding/"
label_path: "/home/shensheng/nlp/try_data/data/" # path to the preprocessed amazon review dir
cur_test: "en_jp/" # choose one language from ["en_jp/", "en_fr/", "en_de/"]
cur_cat: "_music" # choose from '_music', '_dvd', '_books'
nb_feature: [2348, 2304] # embedding shape for other language and english, please do not change
nb_maxlen: [24, 24] # max number of sentences in document
batch_size: 32
epochs: 10
hidden_dim: 64
dropout: 0.5
mode: 'test'